function [newData1] = importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 06-Dec-2017 14:39:50

% Import the file
newData1 = importdata(fileToRead1);

